<?xml version="1.0" encoding="utf-8"?>
<django-objects version="1.0"><object pk="1" model="bugs.milestone"><field type="CharField" name="name">Défaut</field><field type="TextField" name="description">&lt;p&gt;
	Une &amp;eacute;tape par d&amp;eacute;faut.&lt;/p&gt;
</field><field type="SmallIntegerField" name="max_pain_level">50</field><field type="BooleanField" name="public">False</field><field type="BooleanField" name="active">True</field><field type="DateTimeField" name="creation_date">2010-11-16 16:37:54</field><field type="DateTimeField" name="update_date">2010-11-16 16:37:54</field></object><object pk="1" model="bugs.ticket"><field type="CharField" name="name">Un bug simple créer par un utilisateur lambda</field><field type="TextField" name="description">Il y a un problème quelque part.</field><field type="FloatField" name="pain"><None></None></field><field type="SmallIntegerField" name="type"><None></None></field><field type="SmallIntegerField" name="priority"><None></None></field><field type="SmallIntegerField" name="likelihood"><None></None></field><field type="BooleanField" name="active">True</field><field type="SmallIntegerField" name="status">0</field><field to="bugs.component" name="component" rel="ManyToOneRel"><None></None></field><field to="auth.user" name="creator" rel="ManyToOneRel">1</field><field to="auth.user" name="reviewer" rel="ManyToOneRel"><None></None></field><field type="TextField" name="reviewer_note"></field><field to="bugs.milestone" name="planified_to_milestone" rel="ManyToOneRel"><None></None></field><field to="bugs.milestone" name="closed_in_milestone" rel="ManyToOneRel"><None></None></field><field type="DateTimeField" name="creation_date">2010-11-16 16:41:48</field><field type="DateTimeField" name="update_date">2010-11-16 16:41:48</field><field type="BooleanField" name="allow_comments">True</field><field type="TextField" name="contextual_data"></field></object></django-objects>